
#=====================================================
dico_depart = {"longueur élémentaire de croissance" : 1.0,
               "sigma" : 20.0,
               "énergie de base d'une branche" : .0,
               "pourcentage d'énergie de départ (en %)" : .0,
               "nombre minimal de branches générables" : 2,
               "nombre maximal de branches générables" : 5,
               "probabilité qu'une branche grandisse (en %)" : 0,
               "probabilité d'apparition de nouvelles branches (en %)" : 33,
               "croissance pourcent nouvelle branche": 1,
               "probabilité maximal d'apparition de nouvelles branches (en %)" : 66,
               "longévité d'une feuille" : 5,
               "énergie produite par feuille" : 5.0,
               "consommation d'énergie par feuille" : 0.25,
               "décroissance pourcent nouvelle feuille" : 5,
               "probabilité de faire pousser une feuille au départ (en %)" : 80,
               "probabilité de faire pousser une feuille minimale (en %)" : 55,
               "consommation d'énergie pour grandir" : 10.0,
               "consommation d'énergie pour générer une branche" : 5.0,
               "consommation d'énergie pour vivre par branche" : 1.,
               "consommation d'énergie par sous-branches directes" : 0.5,
               "consommation d'énergie pour générer une feuille" : 1.,
               "energie arbre départ": 5.0,
               "ratio" : 24,
               "uniforme" : 1,
               "puissance" : 1.0,
               "delta t": 1000,
               "precision" : 10000
               }

#──────────────────────────────────────────────
liste_nom_var = ["longueur élémentaire de croissance",
                 "sigma",
                 "énergie de base d'une branche",
                 "pourcentage d'énergie de départ (en %)",
                 "nombre minimal de branches générables",
                 "nombre maximal de branches générables",
                 "probabilité qu'une branche grandisse (en %)",
                 "probabilité d'apparition de nouvelles branches (en %)",
                 "croissance pourcent nouvelle branche",
                 "probabilité maximal d'apparition de nouvelles branches (en %)",
                 "longévité d'une feuille",
                 "énergie produite par feuille",
                 "consommation d'énergie par feuille",
                 "décroissance pourcent nouvelle feuille",
                 "probabilité de faire pousser une feuille au départ (en %)",
                 "probabilité de faire pousser une feuille minimale (en %)",
                 "consommation d'énergie pour grandir",
                 "consommation d'énergie pour générer une branche",
                 "consommation d'énergie pour vivre par branche",
                 "consommation d'énergie par sous-branches directes",
                 "consommation d'énergie pour générer une feuille",
                 "energie arbre départ",
                 "ratio",
                 "uniforme",
                 "puissance",
                 "delta t",
                 "precision"]

#──────────────────────────────────────────────
liste_entier = ["longévité d'une feuille",
                "nombre maximal de feuilles par branche",
                "nombre minimal de branches générables",
                "nombre maximal de branches générables",
                "nombre minimal de feuilles pour nouvelles branches",
                "probabilité qu'une branche grandisse (en %)",
                "probabilité d'apparition de nouvelles branches (en %)",
                "probabilité de faire pousser une feuille (en %)",
                "probabilité maximal d'apparition de nouvelles branches (en %)",
                "ratio",
                "uniforme",
                "precision",
                "delta t"]

#=====================================================
